apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-producer
  template:
    metadata:
      labels:
        app: market-producer
    spec:
      containers:
        - name: producer
          image: 045193015451.dkr.ecr.us-east-2.amazonaws.com/crypto-streaming-producer:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: market-pipeline-config
            - secretRef:
                name: market-pipeline-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
